apiVersion: v1
kind: Service
metadata:
  name: {{ lower .Values.name}}
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: {{.Values.servicePort}}
    targetPort: {{.Values.serviceTargetPort}}
    protocol: TCP
  selector:
    app: {{lower .Values.name}}
